import type { Metadata } from "next";
import {Work_Sans,Source_Sans_3} from "next/font/google";
import "./globals.css";


const worksSans=Work_Sans({subsets:['latin'],variable:'--work-sans'})
const sourceSans=Source_Sans_3({subsets:['latin'],variable:'--source-sans'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans.variable} ${worksSans.variable} ${sourceSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
